### PR TITLE
feat: add contributors

### PR DESCRIPTION
**Pull request by tony-go**
Screenshot 2024-11-23 at 13 11 08

### CODE REVIEW

**Comment by jviotti** [comment]
Looking good! Though I find the black background title too much given we also have it on "Looking for expert help" below. What about this simpler take on it?

Screenshot 2024-11-25 at 9 42 14 am

**Comment by jviotti** [comment]
Actually, maybe we can do a vertical split... maybe it will all fit better there. Let me try it out to see

**Comment by jviotti** [comment]
What about re-ordering a bit like this? I think it fits better. What do you think?

Screenshot 2024-11-25 at 9 49 14 am

This is the patch I used, that probably breaks responsiveness 😅 

```diff
diff --git a/content/_index.html b/content/_index.html
index aec2adf..f3ac441 100644
--- a/content/_index.html
+++ b/content/_index.html
@@ -259,94 +259,79 @@ title = "Home"
 
 <section class="py-5 bg-light bg-gradient border-top shadow-sm mt-5">
   <div class="container">
+    <p class="fw-light display-6 mb-5">Meet the minds behind cutting-edge innovations</p>
     <div class="column">
-      <div class="col-12 col-xl-6">
-        <div class="bg-black text-light d-inline-block p-3 mb-4">
-          <h2 class="fw-light display-6 mb-0">Contributors</h2>
-        </div>
-        <p class="lead mb-4">Meet the minds behind cutting-edge innovations</p>
-      </div>
-
       <div class="row">
-        <div class="col-12 col-xl-6 d-flex align-items-start mt-5 mt-xl-0">
-          <div class="flex-shrink-0">
-            <a target="_blank" href="https://github.com/jviotti">
-              <img src="jviotti.jpeg" class="img-thumbnail" width="100" height="100">
-            </a>
-          </div>
-          <div class="ms-4">
-            <h3 class="h5 fw-bold">
-              <span class="me-2">Juan Cruz Viotti</span>
-              <a target="_blank" href="https://www.linkedin.com/in/jviotti/"
-                class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-linkedin"></i>
-              </a>
-              <a target="_blank" href="https://github.com/jviotti" class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-github"></i>
+        <div class="col-6">
+          <div class="d-flex align-items-start mb-5">
+            <div class="flex-shrink-0">
+              <a target="_blank" href="https://github.com/jviotti">
+                <img src="jviotti.jpeg" class="img-thumbnail" width="100" height="100">
               </a>
-              <a target="_blank" href="https://www.jviotti.com" class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-link-45deg"></i>
-              </a>
-            </h3>
-            <small class="mb-0 fw-light">Award winning University of Oxford alumni, O'Reilly author, member of the JSON
-              Schema Technical Steering Committee, 10+ experience as a C++ system engineer, performance and data
-              consultant, binary serialisation expert, ex-contractor at Postman, ex-Engineering Lead at Balena, and
-              creator of the popular Etcher open-source desktop application (within the top 700 public repositories on
-              GitHub).</small>
+            </div>
+            <div class="ms-4">
+              <h3 class="h5 fw-bold">
+                <span class="me-2">Juan Cruz Viotti</span>
+                <a target="_blank" href="https://www.linkedin.com/in/jviotti/"
+                  class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-linkedin"></i>
+                </a>
+                <a target="_blank" href="https://github.com/jviotti" class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-github"></i>
+                </a>
+                <a target="_blank" href="https://www.jviotti.com" class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-link-45deg"></i>
+                </a>
+              </h3>
+              <small class="mb-0 fw-light">Award winning University of Oxford alumni, O'Reilly author, member of the JSON
+                Schema Technical Steering Committee, 10+ experience as a C++ system engineer, performance and data
+                consultant, binary serialisation expert, ex-contractor at Postman, ex-Engineering Lead at Balena, and
+                creator of the popular Etcher open-source desktop application (within the top 700 public repositories on
+                GitHub).</small>
+            </div>
           </div>
-        </div>
 
-        <div class="col-12 col-xl-6 d-flex align-items-start mt-5 mt-xl-0">
-          <div class="flex-shrink-0">
-            <a target="_blank" href="https://standardresume.co/r/tonygo">
-              <img src="tonygorez.jpg" class="img-thumbnail" width="100" height="100">
-            </a>
-          </div>
-          <div class="ms-4">
-            <h3 class="h5 fw-bold">
-              <span class="me-2">Tony Gorez</span>
-              <a target="_blank" href="https://www.linkedin.com/in/tonygorez/"
-                class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-linkedin"></i>
-              </a>
-              <a target="_blank" href="https://github.com/tony-go" class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-github"></i>
-              </a>
-              <a target="_blank" href="https://www.tonygo.tech" class="text-dark text-decoration-none mx-1">
-                <i class="bi bi-link-45deg"></i>
+          <div class="d-flex align-items-start">
+            <div class="flex-shrink-0">
+              <a target="_blank" href="https://standardresume.co/r/tonygo">
+                <img src="tonygorez.jpg" class="img-thumbnail" width="100" height="100">
               </a>
-            </h3>
-            <small class="mb-0 fw-light">As a fellow software engineer, Tony focuses on research and
-              development projects. He is skilled in low-level languages like C, C++, and Swift. He plays a pivotal
-              role on Postman's advanced R&D team, working on innovative desktop framework solutions. Tony's deep
-              interest in macOS internals, debugging, and reverse engineering drives his willingness to gain mastery
-              over the Apple ecosystem.
-            </small>
-
+            </div>
+            <div class="ms-4">
+              <h3 class="h5 fw-bold">
+                <span class="me-2">Tony Gorez</span>
+                <a target="_blank" href="https://www.linkedin.com/in/tonygorez/"
+                  class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-linkedin"></i>
+                </a>
+                <a target="_blank" href="https://github.com/tony-go" class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-github"></i>
+                </a>
+                <a target="_blank" href="https://www.tonygo.tech" class="text-dark text-decoration-none mx-1">
+                  <i class="bi bi-link-45deg"></i>
+                </a>
+              </h3>
+              <small class="mb-0 fw-light">As a fellow software engineer, Tony focuses on research and
+                development projects. He is skilled in low-level languages like C, C++, and Swift. He plays a pivotal
+                role on Postman's advanced R&D team, working on innovative desktop framework solutions. Tony's deep
+                interest in macOS internals, debugging, and reverse engineering drives his willingness to gain mastery
+                over the Apple ecosystem.
+              </small>
+            </div>
           </div>
         </div>
+        <div class="col-6 ps-5">
+          <div class="bg-black text-light d-inline-block p-3 mb-5">
+            <h2 class="fw-light display-5 mb-0">Looking for expert help?</h2>
+          </div>
 
-      </div>
-    </div>
-  </div>
-</section>
+          <p class="lead mb-4">We offer world-class custom ontology design, consulting, development, and training on JSON
+            Schema and APIs.</p>
 
-<section class="py-5 bg-light bg-gradient">
-  <div class="container">
-    <div class="row align-items-xl-center">
-      <div class="col-12 col-xl-6 mb-4 mb-xl-0">
-        <div class="bg-black text-light d-inline-block p-3">
-          <h2 class="fw-light display-5 mb-0">Looking for expert help?</h2>
+          <a class="btn btn-outline-dark" href="mailto:hello@sourcemeta.com" role="button">Get in touch to discuss
+            more</a>
         </div>
       </div>
-
-      <div class="col-12 col-xl-6">
-        <p class="lead mb-4">We offer world-class custom ontology design, consulting, development, and training on JSON
-          Schema and APIs.</p>
-
-        <a class="btn btn-outline-dark" href="mailto:hello@sourcemeta.com" role="button">Get in touch to discuss
-          more</a>
-      </div>
     </div>
   </div>
 </section>
```

**Comment by tony-go** [comment]
yeah @jviotti lessgo, could you please send the patch?

**Comment by jviotti** [comment]
@tony-go I did on the above comment! Feel free to apply it with `git am`, etc

**Review by jviotti — APPROVED** [review]
Looks great!

**Pull request merged**
